// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Node interface {
	IsNode()
}

type FeedBacks struct {
	ID        string  `json:"id"`
	Name      *string `json:"name"`
	Phone     *string `json:"phone"`
	Email     *string `json:"email"`
	Address   *string `json:"address"`
	Content   *string `json:"content"`
	CreatedAt *string `json:"createdAt"`
}

func (FeedBacks) IsNode() {}

type Friend struct {
	ID      string     `json:"id"`
	Friends []*Profile `json:"friends"`
}

func (Friend) IsNode() {}

type InputFeedBacks struct {
	Name    *string `json:"name"`
	Phone   *string `json:"phone"`
	Email   *string `json:"email"`
	Address *string `json:"address"`
	Content *string `json:"content"`
}

type InputMenues struct {
	Text         *string `json:"text"`
	Link         *string `json:"link"`
	DisplayOrder *int    `json:"displayOrder"`
	Target       *string `json:"target"`
}

type InputNewTag struct {
	TagID *int `json:"tagId"`
	NewID *int `json:"newId"`
}

type InputNews struct {
	Title       *string `json:"title"`
	Description *string `json:"description"`
	Image       *string `json:"image"`
	Detail      *string `json:"detail"`
	CreatedAt   *string `json:"createdAt"`
	TopHot      *string `json:"topHot"`
	ViewCount   *int    `json:"viewCount"`
	Content     *string `json:"content"`
	TagID       *int    `json:"tagId"`
	Active      *bool   `json:"active"`
}

type InputProfile struct {
	UserID     *int    `json:"userId"`
	FirstName  *string `json:"firstName"`
	LastName   *string `json:"lastName"`
	Address    *string `json:"address"`
	Phone      *string `json:"phone"`
	CreatedAt  *string `json:"createdAt"`
	ModifiedBy *string `json:"modifiedBy"`
}

type InputTags struct {
	Name *string `json:"name"`
}

type Menues struct {
	ID     string  `json:"id"`
	Text   *string `json:"text"`
	Link   *string `json:"link"`
	Target *string `json:"target"`
}

func (Menues) IsNode() {}

type NewTag struct {
	ID    string  `json:"id"`
	TagID *int    `json:"tagId"`
	NewID *int    `json:"newId"`
	Tags  []*Tags `json:"tags"`
	News  []*News `json:"news"`
}

func (NewTag) IsNode() {}

type News struct {
	ID          string  `json:"id"`
	Title       *string `json:"title"`
	Description *string `json:"description"`
	Image       *string `json:"image"`
	Detail      *string `json:"detail"`
	CreatedAt   *string `json:"createdAt"`
	TopHot      *string `json:"topHot"`
	ViewCount   *int    `json:"viewCount"`
	Content     *string `json:"content"`
	TagID       *int    `json:"tagId"`
	Active      *bool   `json:"active"`
	Tags        []*Tags `json:"tags"`
}

func (News) IsNode() {}

type Profile struct {
	ID        string  `json:"id"`
	UserID    *int    `json:"userId"`
	FirstName *string `json:"firstName"`
	LastName  *string `json:"lastName"`
	Address   *string `json:"address"`
	Phone     *string `json:"phone"`
	CreatedAt *string `json:"createdAt"`
}

func (Profile) IsNode() {}

type ResultCheck struct {
	Status  *bool   `json:"status"`
	Message *string `json:"message"`
}

type ResultFeedBacks struct {
	ID        *int    `json:"id"`
	Name      *string `json:"name"`
	Phone     *string `json:"phone"`
	Email     *string `json:"email"`
	Address   *string `json:"address"`
	Content   *string `json:"content"`
	CreatedAt *string `json:"createdAt"`
}

type ResultFriend struct {
	ID string `json:"id"`
}

type ResultMenues struct {
	ID           *int    `json:"id"`
	Text         *string `json:"text"`
	Link         *string `json:"link"`
	DisplayOrder *int    `json:"displayOrder"`
	Target       *string `json:"target"`
}

type ResultNewTag struct {
	ID    *int `json:"id"`
	TagID *int `json:"tagId"`
	NewID *int `json:"newId"`
}

type ResultNews struct {
	ID          *int    `json:"id"`
	Title       *string `json:"title"`
	Description *string `json:"description"`
	Image       *string `json:"image"`
	Detail      *string `json:"detail"`
	CreatedAt   *string `json:"createdAt"`
	TopHot      *string `json:"topHot"`
	ViewCount   *int    `json:"viewCount"`
	Content     *string `json:"content"`
	TagID       *int    `json:"tagId"`
	Active      *bool   `json:"active"`
}

type ResultProfile struct {
	ID         *int    `json:"id"`
	UserID     *int    `json:"userId"`
	FirstName  *string `json:"firstName"`
	LastName   *string `json:"lastName"`
	Address    *string `json:"address"`
	Phone      *string `json:"phone"`
	CreatedAt  *string `json:"createdAt"`
	ModifiedBy *string `json:"modifiedBy"`
}

type ResultSystemConfig struct {
	ID    *int    `json:"id"`
	Name  *string `json:"name"`
	Type  *string `json:"type"`
	Value *string `json:"value"`
}

type ResultTags struct {
	ID   *int    `json:"id"`
	Name *string `json:"name"`
}

type SystemConfig struct {
	ID    string  `json:"id"`
	Name  *string `json:"name"`
	Type  *string `json:"type"`
	Value *string `json:"value"`
}

func (SystemConfig) IsNode() {}

type Tags struct {
	ID   string  `json:"id"`
	Name *string `json:"name"`
}

func (Tags) IsNode() {}

type Users struct {
	ID         string   `json:"id"`
	Username   *string  `json:"username"`
	Password   *string  `json:"password"`
	UserDetail *Profile `json:"userDetail"`
}

func (Users) IsNode() {}
