// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type FeedBacks struct {
	ID        *int    `json:"id"`
	Name      *string `json:"name"`
	Phone     *string `json:"phone"`
	Email     *string `json:"email"`
	Address   *string `json:"address"`
	Content   *string `json:"content"`
	CreatedAt *string `json:"createdAt"`
}

type InputFeedBacks struct {
	Name    *string `json:"name"`
	Phone   *string `json:"phone"`
	Email   *string `json:"email"`
	Address *string `json:"address"`
	Content *string `json:"content"`
}

type InputProfile struct {
	UserID     *int    `json:"userId"`
	FirstName  *string `json:"firstName"`
	LastName   *string `json:"lastName"`
	Address    *string `json:"address"`
	Phone      *string `json:"phone"`
	CreatedAt  *string `json:"createdAt"`
	ModifiedBy *string `json:"modifiedBy"`
}

type Menues struct {
	ID     *int    `json:"id"`
	Text   *string `json:"text"`
	Link   *string `json:"link"`
	Target *string `json:"target"`
}

type NewTag struct {
	ID    *int    `json:"id"`
	TagID *int    `json:"tagId"`
	NewID *int    `json:"newId"`
	News  []*News `json:"news"`
	Tags  []*Tags `json:"tags"`
}

type News struct {
	ID          int     `json:"id"`
	Title       *string `json:"title"`
	Description *string `json:"description"`
	Image       *string `json:"image"`
	CreatedAt   *string `json:"createdAt"`
	TopHot      *string `json:"topHot"`
	ViewCount   *int    `json:"viewCount"`
	Content     *string `json:"content"`
	TagID       *int    `json:"tagId"`
	Active      *bool   `json:"active"`
	Tags        []*Tags `json:"tags"`
}

type Profile struct {
	ID        *int    `json:"id"`
	UserID    *int    `json:"userId"`
	FirstName *string `json:"firstName"`
	LastName  *string `json:"lastName"`
	Address   *string `json:"address"`
	Phone     *string `json:"phone"`
	CreatedAt *string `json:"createdAt"`
}

type ResultCheck struct {
	Status  *bool   `json:"status"`
	Message *string `json:"message"`
}

type Tags struct {
	ID   *int    `json:"id"`
	Name *string `json:"name"`
}

type Users struct {
	ID         *int     `json:"id"`
	Username   *string  `json:"username"`
	Password   *string  `json:"password"`
	UserDetail *Profile `json:"userDetail"`
}
