// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Node interface {
	IsNode()
}

type FeedBacks struct {
	ID        string  `json:"id"`
	Name      *string `json:"name"`
	Phone     *string `json:"phone"`
	Email     *string `json:"email"`
	Address   *string `json:"address"`
	Content   *string `json:"content"`
	CreatedAt *string `json:"createdAt"`
}

func (FeedBacks) IsNode() {}

type InputFeedBacks struct {
	Name    *string `json:"name"`
	Phone   *string `json:"phone"`
	Email   *string `json:"email"`
	Address *string `json:"address"`
	Content *string `json:"content"`
}

type Menues struct {
	ID           string  `json:"id"`
	Text         *string `json:"text"`
	Link         *string `json:"link"`
	DisplayOrder *int    `json:"displayOrder"`
	Target       *string `json:"target"`
}

func (Menues) IsNode() {}

type NewTag struct {
	ID    string  `json:"id"`
	TagID *int    `json:"tagId"`
	Name  *string `json:"name"`
}

func (NewTag) IsNode() {}

type News struct {
	ID              string  `json:"id"`
	Title           *string `json:"title"`
	MetaTitle       *string `json:"metaTitle"`
	Description     *string `json:"description"`
	Image           *string `json:"image"`
	CategoryID      *int    `json:"categoryId"`
	Detail          *string `json:"detail"`
	CreatedAt       *string `json:"createdAt"`
	CreatedBy       *string `json:"createdBy"`
	ModifiedData    *string `json:"modifiedData"`
	ModifiedBy      *string `json:"modifiedBy"`
	MetaKeyWord     *string `json:"metaKeyWord"`
	MetaDescription *string `json:"metaDescription"`
	TopHot          *string `json:"topHot"`
	ViewCount       *int    `json:"viewCount"`
	Content         *string `json:"content"`
	TagID           *int    `json:"tagId"`
	Active          *bool   `json:"active"`
	Tags            []*Tags `json:"tags"`
}

func (News) IsNode() {}

type Profile struct {
	ID           string  `json:"id"`
	UserID       *string `json:"userId"`
	FirstName    *string `json:"firstName"`
	LastName     *string `json:"lastName"`
	Address      *string `json:"address"`
	Phone        *string `json:"phone"`
	CreatedAt    *string `json:"createdAt"`
	CreatedBy    *string `json:"createdBy"`
	ModifiedDate *string `json:"modifiedDate"`
	ModifiedBy   *string `json:"modifiedBy"`
}

func (Profile) IsNode() {}

type ResultCheck struct {
	Status  *bool   `json:"status"`
	Message *string `json:"message"`
}

type ResultNewTag struct {
	ID    string  `json:"id"`
	TagID *int    `json:"tagId"`
	Name  *string `json:"name"`
}

type ResultTags struct {
	ID    string  `json:"id"`
	Name  *string `json:"name"`
	NewID *int    `json:"newId"`
}

type Tags struct {
	ID     string    `json:"id"`
	Name   *string   `json:"name"`
	NewID  *int      `json:"newId"`
	News   []*News   `json:"news"`
	NewTag []*NewTag `json:"newTag"`
}

func (Tags) IsNode() {}

type Users struct {
	ID         string   `json:"id"`
	Username   *string  `json:"username"`
	Password   *string  `json:"password"`
	UserDetail *Profile `json:"userDetail"`
}

func (Users) IsNode() {}
